### ISSUE TITLE
desktop notifications not working

### ISSUE THREAD

**Issue by qiuness** [selam/bitcoinwisdom-sound-alerter#1]
i wanted this script to get desktop notifications, but that does not trigger.. Any thoughts?

**Comment by selam** [comment]
Hi,  when i write this extension notification api wasnt published by W3C, however after html5 spec release some of old vendored methods/calls etc changed, in these time of period bitcoinwisdom added sound alert functionality in their web site and i lost my interest over this extension for that

i dont have too much time on pc for personal reason but i will fix in one week.

**Comment by qiuness** [comment]
Hello and thanks for answering. I found the extension useful because for
some reason sound alerts on bitcoinwisdom stopped working (i`m not the only
one). I have 2 questions if i may:
1. Will the extension upgrade automatically once you change it?
2. Can i change the sound used?

Cheers

**Comment by selam** [comment]
Hi,

Your welcome.

1) yes it will be update automaticly but it will be silent,  probably you
dont realize this update,  after i push the update to google and github i
will close this issue and youll notified by github, then you can update
manually from webstore.

2) yes you can but why? You dont like to road runner? However, it will be
hacky, i am using linux and i will explain for linux;
google chrome or chromium's extensions   stays in
.config/chromium/Default/Extensions or
.config/google-chrome/Default/Extensions
When you find where is your extensions look  this directory
"fmhacmihfjdgiikjcghjmffajebcgjpb"  inside of this directory you can see
sounds dir. You can change this files but names must stay same.

More easy to find these files on your computer search this file names;
"nooo.mp3" or "road_runner.mp3". Maybe you need to close/open your browser
i am not sure.

I will update this extension to nigth (gmt +3) if i have time.

On Wednesday, April 13, 2016, qiuness notifications@github.com wrote:

> Hello and thanks for answering. I found the extension useful because for
> some reason sound alerts on bitcoinwisdom stopped working (i`m not the only
> one). I have 2 questions if i may:
> 1. Will the extension upgrade automatically once you change it?
> 2. Can i change the sound used?
> 
> Cheers
> 
> On Tue, Apr 12, 2016 at 11:47 PM, Timu Eren <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Hi, when i write this extension notification api wasnt published by W3C,
> > however after html5 spec release some of old vendored methods/calls etc
> > changed, in these time of period bitcoinwisdom added sound alert
> > functionality in their web site and i lost my interest over this
> > extension
> > for that
> > 
> > i dont have too much time on pc for personal reason but i will fix in one
> > week.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/selam/bitcoinwisdom-sound-alerter/issues/1#issuecomment-209095533
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/selam/bitcoinwisdom-sound-alerter/issues/1#issuecomment-209101715

## 

Saygılar && İyi Çalışmalar
Timu EREN ( a.k.a selam )

**Comment by selam** [comment]
Hi, 

I update this extension, it will be available for download in one hour. old version was 0.6, now is 0.7

**Comment by qiuness** [comment]
Hi. That was fast! Thanks a lot.. I could not test it because bitcoinwisdom
is down!
